### ISSUE TITLE
Comments shouldn't appear as a block

### ISSUE THREAD

**Issue by vanbang9710** [BumbrT/obsidian-reading-comments#14]
I hope it can be inline like the [comment plugin](https://github.com/Darakah/obsidian-comments-plugin)

![image](https://user-images.githubusercontent.com/52906188/217580653-53280b2c-721f-46fb-b6ea-f0198447f735.png)

**Comment by BumbrT** [comment]
Appreciate if you suggest HTML markup for comment with CSS based hide/show implementation. I've tried \<span\> container, but I don't like behavior when comment disappear when cursor placed between lines. Block solved this problem.

**Comment by BumbrT** [comment]
You can replace \<div\> with the \<span\> in multi-line comment and move cursor up and down on top of the comment. Or i can attach gif to demonstrate   this odd behavior when cursor placed between lines in inline markup.

**Comment by BumbrT** [comment]
Or i can just add container option in the settings.

**Comment by BumbrT** [comment]
Added to settings: \<div\> or \<span\> container for comments. Also added two additional commands: inline and block comment.

**Comment by vanbang9710** [comment]
Did you mean the comment placeholder disappearing and reappearing when moving the cursor between 2 lines? It does look a bit annoying but I guess I can endure it.

**Comment by BumbrT** [comment]
Yes, exactly. Appreciate if someone would be able to find CSS solution for this.
