### ISSUE TITLE
Feature Request: Place Cursor at Placeholder

### ISSUE THREAD

**Issue by julroger2013** [BumbrT/obsidian-reading-comments#34]
What a great plugin! I've been looking for a good way to add comments to markdown documents for forever. 

One feature request, if you don't mind. Right now, on inserting a comment, the cursor appears at the end of the HTML tag. Would it be possible to make it so that the cursor instead jumps to where the "CommentPlaceholder" text now appears? 

It would be a little easier if the cursor appeared here so that the user could begin typing immediately upon inserting a comment, rather than needing to mouseclick/arrow-over into the CommentPlaceholder portion of the tag. 

Thanks again for making this! It works really well.

**Comment by BumbrT** [comment]
Thank you for the positive review! I will look at it, and will be back with the result in few days

**Comment by BumbrT** [comment]
Added in 1.0.15 release
