### ISSUE TITLE
[Feature request]: Show comments in a hover window

### ISSUE THREAD

**Issue by marsvet** [BumbrT/obsidian-reading-comments#37]
Thanks to the author! I've been looking for a similar plugins for a long time, but I couldn't find a good one. Now, I've finally found this plugin.

Could you add this feature: show comments in a hover window, just like "Ctrl + 'hover the mouse cursor over the link'" in obsidian, I think it might be a better presentation.

I would be grateful if you could consider adding this feature in the future.

**Comment by BumbrT** [comment]
Hey! For now as a workaround, you can "extract original note" and it will work in a way you want. I will investigate options to implement this feature

**Comment by marsvet** [comment]
Thank you very much.

**Comment by BumbrT** [comment]
In 1.0.17 added setting to show comment by Ctrl + Hover. Still have problems with showing comment content in a way you suggested. Will appreciate if someone will drop example or draft implementation of how to show comment in hover window.

**Comment by BumbrT** [comment]
Found HoverPopover in the Obsidian API https://github.com/obsidianmd/obsidian-api/blob/bceb489fc25ceba5973119d6e57759d64850f90d/obsidian.d.ts#L1590
Will implement a bit later

**Comment by marsvet** [comment]
Hahaha, that's fantistic!

**Comment by BumbrT** [comment]
Done in 1.0.18! Looks like it works.

**Comment by BumbrT** [comment]
Improved behavior of popup in 1.0.19, looks like it perfect now 💯   Closing this feature request.

**Comment by marsvet** [comment]
Yes, It's so perfect. 😄
