### ISSUE TITLE
[Feature request]: Pin comments and Edit comments in the hover window

### ISSUE THREAD

**Issue by u2003** [BumbrT/obsidian-reading-comments#45]
Thanks for your kind contribution! The plugin I've always longed for!
I wonder if you could consider adding a floating bar to pin the popup window of the comments and then edit it. I suppose that would be more friendly to users.
I would highly highly appreciate it if you could please take this feature into account!

**Comment by BumbrT** [comment]
I will consider this feature, but for now implementation looks too complicated and will consume too much my time.
What problem are you trying to solve?
Pin few comments and edit them simultaneously?
Please provide your main pain point, maybe I will be able to suggest cheaper solution in terms of implementation cost.

**Comment by BumbrT** [comment]
BTW obsidian recently released "Bookmarks" plugin, it has similar functionality and has popups for edits.
