### ISSUE TITLE
这个插件是不是不支持中文？

### ISSUE THREAD

**Issue by chenxin0397** [BumbrT/obsidian-reading-comments#46]
![image](https://github.com/BumbrT/obsidian-reading-comments/assets/73974352/21856f48-2ec1-4eb6-9cdc-9d796da57ae2)

**Comment by chenxin0397** [comment]
感觉慢一步，
当我添加第一个comment，它不显示
当我添加第二个comment，它显示第一个comment
当我删除第二个comment，它显示第二个comment
我很无语……

**Comment by BumbrT** [comment]
Hey, looks like you closed the issue. Hope everything is fine. As is understood with translation, sometimes comments not get updated in the side panel. I can investigate it, if you will provide how to exactly reproduce the issue.

**Comment by chenxin0397** [comment]
好像只是延迟，需要该文档的内容再次被修改才能更新

**Comment by BumbrT** [comment]
Yes, comments panel is just a function of the document content. I will look at how to improve panel update logic. Maybe just will add a timer to update it every minute, or something like this.

**Comment by chenxin0397** [comment]
谢谢，你真是很用心的开发者！

**Comment by BumbrT** [comment]
Released in 1.0.23 version
