### ISSUE TITLE
[Feature request]: optional icon next to commented text 

### ISSUE THREAD

**Issue by a-rock-lobster** [BumbrT/obsidian-reading-comments#51]
Firstly, thanks for sharing. Really helpful.

I would like to suggest an optional icon such as a sticky note next to commented text to help differentiate commented text from highlighted text when also using the Highlightr plugin. One could say, well use a different colour for the Reading Comments highlighted text. This is fine except for those who use intricate systems to colour code information and use a lot of highlighter colours already (ahem, like me). A little in-line icon such as RiStickyNoteLine would be helpful here. 

I hope I explained that sufficiently clearly.

Best,

Haydn

**Comment by BumbrT** [comment]
Hey,
I will look at it, maybe will add toggle option for icon. But this is narrow customization request.
For now you can play with css styles and add custom style with icon for ".ob-html-comment" style.
Here is the example: https://stackoverflow.com/questions/29576527/adding-icon-image-to-css-class-for-html-elements

Example of comment html is in the Readme:
`<div class="ob-html-comment" id="comment-${commentId}" data-tags="[comment,]"><span class="ob-html-comment-body">CommentPlaceholder</span>${htmlEscapedSelection}</div>`

**Comment by a-rock-lobster** [comment]
Thanks for that info. I will have a play. This is pushing the limits of my css capabilities but it's good to learn. 

Yeah, I was thinking as I wrote it that it was niche.

**Comment by BumbrT** [comment]
Yep, I will drop example here when I will have time to play with it. But for now you can try something like ChatGPT , it has some css skills :)

**Comment by BumbrT** [comment]
Hey!
Added How To section to readme: https://github.com/BumbrT/obsidian-reading-comments#how-to-add-icon-next-to-commented-text

**Comment by a-rock-lobster** [comment]
Neat! Thank you. My own attempts had ended up less than satisfactory.
