### ISSUE TITLE
[Feature Request] Support Obsidian Comment Syntax

### ISSUE THREAD

**Issue by zhandao** [BumbrT/obsidian-reading-comments#55]
Hi, thanks for such an amazing plugin!

Sometimes, I don't want to use heavy HTML syntax in my markdown, but really need the comments panel, extract, search... of your plugin.

I wonder if supporting Obsidian native comment syntax (`%%...%%`) will waste too much of your time? 

Thanks and best wishes!

**Comment by BumbrT** [comment]
Hey!
I will investigate this one. But for sure it's a breaking change, because all logic is based around HTML and there is no convenient way for comments in markdown. When I investigated native comments in obsidian, it looked as something experimental and not ready yet for broader use.
You can use "Extract original note" feature to get rid of HTML.

**Comment by BumbrT** [comment]
Recently they added "callouts" with [foldable callouts](https://help.obsidian.md/Editing+and+formatting/Callouts#Foldable+callouts). This could work.

**Comment by zhandao** [comment]
Oh I also noticed foldable callouts, actually I'm already using it as hidden comments.
(most of time I still use `%%` syntax)

But there seems no plugin that can quickly view and jump to callouts and comments, just like your panel.

**Comment by BumbrT** [comment]
If will have time, I will try to add %% comments and callouts parsing, but comments will be without tags, and callouts will be grouped by callout tag

**Comment by zhandao** [comment]
Thanks a lot!

**Comment by BumbrT** [comment]
Added parsing %%comments%% in the latest release

**Comment by zhandao** [comment]
> Added parsing %%comments%% in the latest release

works great! 🎉

**Comment by BumbrT** [comment]
If you have an holistic idea, how to accomodate callouts in the commenting workflow, feel free to write it here.

**Comment by zhandao** [comment]
OK, I will.
