### ISSUE TITLE
The text in the comments panel is also white in light mode

### ISSUE THREAD

**Issue by hedonglilv** [BumbrT/obsidian-reading-comments#62]
The text in the comments panel is also white in light mode, making it difficult to read. Can this problem be solved?
![b3a8dab1650011988a34d76cee08b9c](https://github.com/user-attachments/assets/02329636-ea6c-46d8-a7b4-af4b44649f24)

![d5283310fa1f11ac65333ffeeb0647a](https://github.com/user-attachments/assets/f4f8aa69-83cf-44d5-ad92-88e3f1b1690b)

**Comment by BumbrT** [comment]
Yes, I will look at it

**Comment by hedonglilv** [comment]
Thank you for your attention to this matter.
